spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/studydb
      username: root
      password: mysql5717
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

